name: Skylanders.nl
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24985
title: Skylanders.nl
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4e5e3'
    - '#091448'
    - '#2f86bb'
    - '#89c1d6'
    - '#c8978c'
  brandStrength: 0.40430646506138146
  lightness: 0.7594781145453453
  saturation: 0.01234305719844997
  rhythmicContrast: 0.5014466720167547
purpose: []
